#!/usr/bin/env bash
# §16 forbidden-edit guard: CHANGELOG.md is generated by the release
# pipeline (see scripts/generate-changelog.sh and .github/workflows/
# release.yml) and must not be edited by hand. The only legitimate
# edit is the one made on the release branch itself, which carries a
# `chore(release):` commit subject.
#
# This hook is called by pre-commit when CHANGELOG.md is staged.
# It exits non-zero (failing the commit) unless the commit message
# starts with `chore(release):`.
set -euo pipefail

msg_file=".git/COMMIT_EDITMSG"
if [ ! -f "$msg_file" ]; then
  # No commit message yet — pre-commit runs before commit-msg, so
  # we can only catch this when re-running the hook from the
  # commit-msg stage. Skip silently here.
  exit 0
fi

first_line=$(head -n 1 "$msg_file")
case "$first_line" in
  "chore(release):"*|"chore(release)"*"!:"*)
    exit 0
    ;;
  *)
    echo "error: CHANGELOG.md is generated by the release pipeline." >&2
    echo "       Do not edit it by hand. See scripts/generate-changelog.sh." >&2
    exit 1
    ;;
esac
