//! spotifai permissions file (`~/.spotifai/permissions.toml`).
//!
//! This is a thin TOML policy that the `ask` command injects into the
//! agent's system prompt so it self-restricts to the listed `spotifai
//! api` verbs. It is not a substitute for zad's own signed
//! permissions file at `~/.zad/services/spotify/permissions.toml` —
//! that is the authoritative runtime gate. spotifai's file just tells
//! the LLM what surface area to use.
//!
//! TODO: real enforcement. The cleanest path is an upstream change to
//! zad: a `ZAD_PERMISSIONS_PATH` env var that overrides zad's path
//! lookup so spotifai can point it at a translated, zad-schema copy
//! of this file. spotifai's `api::forward` would then set the env
//! var on every shelled-out invocation. Until that ships, the
//! policy is advisory — the system prompt threads it through to the
//! agent, but zad still consults `~/.zad/services/spotify/...` for
//! the actual gate. See zad `docs/permissions.md` for the trust
//! model and signature requirements that the override would have to
//! preserve.
//!
//! The file ships with a read-only default: every `playlists *` and
//! `library * save/unsave` verb is on the deny list, and only the
//! read-side `search`, `playlists list/show`, `library * list` verbs
//! are allowed. Users can hand-edit the file later to widen the
//! surface — there is no signature, by design, so the only thing
//! standing between an edit and the agent picking it up is a
//! re-invocation of `spotifai ask`.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, anyhow};
use serde::{Deserialize, Serialize};

/// Default policy file relative to the spotifai home dir
/// (`~/.spotifai/permissions.toml`).
pub const PERMISSIONS_FILENAME: &str = "permissions.toml";

/// Mode tag stored in the file. Today only `read_only` is generated by
/// default; the field is preserved verbatim on read so future modes can
/// be added without breaking older files.
pub const MODE_READ_ONLY: &str = "read_only";

/// Parsed contents of `~/.spotifai/permissions.toml`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Permissions {
    /// Short tag (`read_only`, `read_write`, …). Informational — the
    /// effective policy is the `allowed` / `denied` lists below.
    pub mode: String,
    /// Free-text description embedded in the system prompt so the agent
    /// can quote the policy back to the user verbatim.
    pub description: String,
    /// `spotifai api` verbs the agent is allowed to invoke. Each entry
    /// is the literal subcommand string after `spotifai api ` (e.g.
    /// `playlists list`, `search`).
    #[serde(default)]
    pub allowed: Vec<String>,
    /// `spotifai api` verbs the agent must refuse to invoke.
    #[serde(default)]
    pub denied: Vec<String>,
}

impl Permissions {
    /// Read-only starter policy written by `spotifai install` if no
    /// permissions file exists yet.
    pub fn read_only_default() -> Self {
        Self {
            mode: MODE_READ_ONLY.to_string(),
            description:
                "Read-only access to the Spotify library. The agent may search the catalogue and \
                 read playlists, saved tracks, and saved albums, but must not create, modify, or \
                 delete anything."
                    .to_string(),
            allowed: vec![
                "search".into(),
                "playlists list".into(),
                "playlists show".into(),
                "library tracks list".into(),
                "library albums list".into(),
            ],
            denied: vec![
                "playlists create".into(),
                "playlists rename".into(),
                "playlists delete".into(),
                "playlists add".into(),
                "playlists remove".into(),
                "library tracks save".into(),
                "library tracks unsave".into(),
                "library albums save".into(),
                "library albums unsave".into(),
            ],
        }
    }

    /// Render the policy as a Markdown block ready to paste into the
    /// agent's system prompt. Used by [`crate::ask`].
    pub fn as_prompt_block(&self) -> String {
        let mut out = String::new();
        out.push_str(&format!("Mode: {}\n", self.mode));
        out.push_str(&format!("Policy: {}\n\n", self.description));
        out.push_str("Allowed `spotifai api` verbs:\n");
        if self.allowed.is_empty() {
            out.push_str("- (none)\n");
        } else {
            for v in &self.allowed {
                out.push_str(&format!("- `spotifai api {v}`\n"));
            }
        }
        out.push_str("\nDenied `spotifai api` verbs (refuse the user if asked):\n");
        if self.denied.is_empty() {
            out.push_str("- (none)\n");
        } else {
            for v in &self.denied {
                out.push_str(&format!("- `spotifai api {v}`\n"));
            }
        }
        out
    }
}

/// Default location: `<dirs::home_dir()>/.spotifai/permissions.toml`.
pub fn default_path() -> Result<PathBuf> {
    let home = dirs::home_dir().ok_or_else(|| anyhow!("could not resolve home directory"))?;
    Ok(home.join(".spotifai").join(PERMISSIONS_FILENAME))
}

/// Serialize a [`Permissions`] to a TOML string with a leading comment
/// header so a curious user opening the file knows what it is.
pub fn to_toml_string(p: &Permissions) -> Result<String> {
    let body = toml::to_string_pretty(p).context("serializing permissions to TOML")?;
    Ok(format!("{}{body}", file_header()))
}

fn file_header() -> &'static str {
    "# spotifai permissions — guides the LLM agent embedded in `spotifai ask`.\n\
     #\n\
     # This file is read by spotifai and injected into the agent's system\n\
     # prompt so it self-restricts to the listed verbs. It does NOT replace\n\
     # zad's own runtime enforcement at\n\
     # `~/.zad/services/spotify/permissions.toml`. Edit `allowed` / `denied`\n\
     # to widen or narrow the surface; spotifai re-reads the file on every\n\
     # `spotifai ask` invocation.\n\n"
}

/// Parse a permissions file from a TOML string.
pub fn from_toml_string(s: &str) -> Result<Permissions> {
    toml::from_str(s).context("parsing permissions TOML")
}

/// Read the permissions file at `path`. Returns the in-memory default
/// (`read_only_default()`) if the file does not exist, so callers can
/// blindly inject without first checking for presence.
pub fn read_or_default(path: &Path) -> Result<Permissions> {
    match fs::read_to_string(path) {
        Ok(s) => from_toml_string(&s),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Permissions::read_only_default()),
        Err(e) => Err(anyhow::Error::new(e).context(format!("reading {}", path.display()))),
    }
}

/// Write the read-only default file at `path` if it does not already
/// exist. Returns `true` if a file was written, `false` if one was
/// already there. Creates parent directories as needed.
pub fn ensure_default(path: &Path) -> Result<bool> {
    if path.exists() {
        return Ok(false);
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
    }
    let s = to_toml_string(&Permissions::read_only_default())?;
    fs::write(path, s).with_context(|| format!("writing {}", path.display()))?;
    Ok(true)
}
